### ISSUE TITLE
Funny Error when trying to access home page after login

### ISSUE THREAD

**Issue by minedun6** [BKWLD/decoy#12]
I'm getting this odd error for an unknown reason.

`fopen(C:\Users\AIO2\Sites\DecoySample\public\/img/temp/home-marquee.jpg): failed to open stream: No such file or directory (View: C:\Users\AIO2\Sites\DecoySample\vendor\bkwld\decoy\views\elements\index.haml)`

Maybe I'm missing something.

**Comment by weotch** [comment]
I tagged a fix for this as 5.2.2, you'll have to delete your `config/decoy/elememts.yaml` file and republish it ( `php artisan vendor:publish --provider="Bkwld\Decoy\ServiceProvider"`).  

The issue was that yaml file contains examples of all of the Elements options, but some of them don't work out of the box (they reference example paths to images that don't actually exist).  Now that yaml has those lines commented out.
