### ISSUE TITLE
Elements migration doesn't create locale_group column.

### ISSUE THREAD

**Issue by SomosAMambo** [BKWLD/decoy#24]
Hi Guys, I know it's just create a migration to solve it. But it's the expected default behavior.

Anyways, here is the migration to update the table `2017_03_27_174854_add_locale_group_to_elements.php`:
```php
<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddLocaleGroupToElements extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('elements', function (Blueprint $table) {
            $table->string('locale_group')->index();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('elements', function (Blueprint $table) {
            $table->dropColumn('locale_group');
        });
    }
}
```

**Comment by SomosAMambo** [comment]
By the way... the team is in love with decoy. So simple and elegant. Non destructive. We hope we can contribute anyway we can to make this the number 1 Laravel CMS.

**Comment by weotch** [comment]
Elements actually shouldn't need that column because there is no need to keep track of the different localized versions of a record.  Elements are essentially key-value pairs and so the key and the locale column are sufficient.

Do you encounter any issue with Elements and localization?

I'm gonna add some tests right now specifically for Elements in the context of localization.

**Comment by SomosAMambo** [comment]
Yeap... Laravel gets a fatal error when saving elements with locales.

**Comment by weotch** [comment]
Can you post your elements yaml files?  And what the error is?  Thanks!

**Comment by weotch** [comment]
Sweet, lemme know if it crops up again.
