### ISSUE TITLE
Support for multiple images

### ISSUE THREAD

**Issue by mindmergedesign** [BKWLD/decoy#50]
Is there a way to add multiple images to an image field? If not, what it would be the best way to accomplish this?

**Comment by noxify** [comment]
I think it's currently not implemented.

But i think we can implement a new custom field..
For example: http://www.dropzonejs.com/bootstrap.html

With this, we can (if i'm not wrong) use the existing upload functionality.

**Comment by mindmergedesign** [comment]
Thanks for the info. I'll give it a try.

**Comment by noxify** [comment]
But i think it's easier to use the dropzonejs sources and create a new custom field instead of using the referenced laravel package.

Maybe a alternative to the dropzonejs is:

https://sroze.github.io/backbone-upload-manager/

or maybe one of them: https://colorlib.com/wp/jquery-file-upload-scripts/

**Comment by weotch** [comment]
What we usually do is create a sub model for the many images we want to associate to a record. For instance, if we have an Article model, we'll create a Photo model that relates as a one to many and use it as a gallery on the article.

**Comment by toddvalentine** [comment]
@weotch could you be a little more specific in regards to how you set up your controllers and interface for this? Do you have the admin user create a new Photo for each image they want to associate with the Article or do you bulk upload in some way? I have tried to create a gallery that has many images and allow for bulk upload (via Dropzone) on the gallery edit page. Dropzone creates an ajax request to my Photos controller, but the wildcard router assumes I am making a POST to the galleries controller since we are on the galleries/{id}/edit view.

**Comment by weotch** [comment]
I would typically have an Articles controller and a Photos controller.  I would use the `form` layout time for the listing element on the Article edit page to make my photos list.  For instance:

```haml
!= Former::text('title')
!= Former::wysiwyg('body')
!= Former::listing('App\Photo')->take(30)->layout('form');
```

If the Photo edit view only had a single a Image field, that is a lot of clicking around for the admin to upload a bunch of images at once, though.  I have not used Dropzone before, but what I'd probably do to support that is define my own Laravel route for it, like in the regular Laravel routes file.  Like maybe `galleries/{id}/dropzone`.  Since the Decoy route registration is designed to come after the main routes, your dropzone route would be executed before the wildcard router.  The dropzone route would point to a special method I'd add to the `Admin\GalleriesController`.

**Comment by eminos** [comment]
An awesome thing would be to extend the Former::listing to display a grid layout, instead of the default (and only?) table layout. That would be nice for image galleries. A drag n drop to that grid listing, to be able to upload multiple files would be amazing too. Something like this would be the goal (at least in my head): https://www.modmore.com/moregallery/

Maybe even to extend the build in Image model and hasImages trait to be able to use that for galleries and direct relation with other models (instead of creating a separate Photos model that hasImages). I don't know if that is even possible.

I'm starting to love Decoy and would love to be able to help extend it and learn more about how to extend it and maybe build my own Former fields to share with the community. I have so many questions, but I'll open up other issues for those.

Is there a Slack community for Decoy? Maybe you guys at Bukwild don't want too much support work in a chat room? :)

**Comment by toddvalentine** [comment]
@weotch yeah, that is what I have done. I have registered a custom route and placed before registerAll. In my gallery edit page I check if the item (gallery) exists and then show my photos Dropzone interface if it does. Using XDebug, it seems that when I hit my Photos Controller method via ajax, Decoy first hits the Galleries update method in the Base Controller as a POST request, then hits my custom route. Is this the expected behavior? Seems a bit strange to me. I have also placed break points in the Auth middleware and it confirms that Decoy is using the wildcard router first, then using the detect explicit route method.
